from users import insertUser, updateFavouriteGenres, getUser
from conversations import addToConversation, newConversation, getUserConversations, getSpecificUserConversation
from db_connection import connection