"""

Shared functions file

Functions that are used across multiple database files

"""

"""Returns the genre ID for a genre name.
@param {String} genre -
@returns {Int} genreID
"""
def getGenre(genre):
    return {
        'action': 1,
        'adult': 2,
        'adventure': 3,
        'animation': 5,
        'biography': 6,
        'comedy': 7,
        'crime': 8,
        'documentary': 9,
        'drama': 10,
        'family': 11,
        'fantasy': 12,
        'film-noir': 13,
        'game-show': 14,
        'history': 15,
        'horror': 16,
        'music': 17,
        'musical': 18,
        'mystery': 19,
        'news': 20,
        'romance': 21,
        'sci-fi': 22,
        'short': 23,
        'sport': 24,
        'superhero': 25,
        'talk-show': 26,
        'thriller': 27,
        'war': 28,
        'western': 29
    }.get(genre, None)


"""
List of superhero titles that were taken from the IMDB website as they were not in the dataset
"""

superhero_titles = [
    "Aquaman", "Spider-Man: Into the Spider-Verse", "Hellboy", "Men in Black: International", "Venom", "Avengers: Endgame",
    "Avengers: Infinity War", "Deadpool 2", "Captain Marvel", "Justice League", "Glass",
    "Spider-Man: Far From Home", "Incredibles 2", "Black Panther", "Hellboy", "Ant-Man and the Wasp",
    "Thor: Ragnarok", "Jingle All the Way", "Shazam!", "Dark Phoenix", "Spider-Man: Homecoming",
    "Suicide Squad", "Wonder Woman", "The Dark Knight", "Split", "Hellboy II: The Golden Army",
    "Guardians of the Galaxy: Vol. 2", "Batman v Superman: Dawn of Justice", "Deadpool", "X-Men: Apocalypse", "Avengers Assemble",
    "The Dark Knight Rises", "Doctor Strange", "Guardians of the Galaxy", "Avengers: Age of Ultron", "Watchmen",
    "Spider-Man", "Captain America: Civil War", "The Incredibles", "Logan", "Iron Man",
    "Captain America: The First Avenger", "Ant-Man", "Unbreakable", "The Mask", "Batman Begins",
    "Man of Steel", "Spider-Man 3", "The Amazing Spider-Man 2", "Iron Man 3", "The New Mutants",
    "Thor", "Captain America: The Winter Soldier", "The Amazing Spider-Man", "V for Vendetta", "Kick-Ass",
    "Thor: The Dark World", "Iron Man 2", "Ghost in the Shell", "Power Rangers", "X-Men Origins: Wolverine",
    "X-Men: Days of Future Past", "Spider-Man 2", "Birdman or (The Unexpected Virtue of Ignorance)", "The Incredible Hulk", "X: First Class",
    "Big Hero 6", "Batman", "Batman Returns", "Superman", "X-Men",
    "Green Lantern", "The Lego Batman Movie", "Teen Titans Go! To the Movies", "Justice League Part Two", "Kick-Ass 2",
    "Tron", "Batman Forever", "Constantine", "Teenage Mutant Ninja Turtles", "Men in Black II",
    "Flash Gordon", "Batman &amp; Robin", "Matrix Reloaded", "The Lego Movie", "Wanted",
    "Fantastic Four", "Kill Bill: Vol. 2", "X-Men: The Last Stand", "Superman Returns", "Blade",
    "The Batman", "Hercules", "Deadpool 3", "Movie 43", "Daredevil",
    "Hulk", "Teenage Mutant Ninja Turtles: Out of the Shadows", "The Wolverine", "The Punisher", "Elektra",
    "X-Men 2", "RoboCop", "Matrix Revolutions", "Teenage Mutant Ninja Turtles", "Blade II",
    "Megamind", "Hancock", "Fantastic Four", "Spawn", "Masters of the Universe",
    "X-Force", "Role Models", "Sky High", "Blade: Trinity", "Jay and Silent Bob Strike Back",
    "Ghost Rider", "Spawn", "The Lone Ranger", "Guardians", "Flashpoint",
    "Superman III", "The Adventures of Sharkboy and Lavagirl 3-D", "Dragonball Evolution", "Supergirl", "The Mask of Zorro",
    "Catwoman", "Jumper", "Superman II", "Fantastic 4: Rise of the Silver Surfer", "The Lego Ninjago Movie",
    "The League of Extraordinary Gentlemen", "TRON", "Epic Movie", "Push", "Punisher: War Zone",
    "Bloodshot", "Batman Ninja", "Howard: A New Breed of Hero", "Ghost Rider: Spirit of Vengeance", "Mystery Men",
    "Astro Boy", "Judge Dredd", "Black Widow", "Rocketeer", "Jonah Hex",
    "Son of the Mask", "Barb Wire", "Superman IV: The Quest for Peace", "The SpongeBob Movie: Sponge Out of Water", "Captain Underpants: The First Epic Movie",
    "The Green Hornet", "Dong wu shi jie", "Super", "The Spirit", "Darkman",
    "Teenage Mutant Ninja Turtles III", "Padman", "RoboCop 2", "Stir of Echoes", "Green Lantern Corps",
    "The Punisher", "The Avengers", "Chicken Little", "The Legend of Zorro", "The Phantom",
    "The Toxic Avenger", "Gambit", "Batman: The Killing Joke", "Swamp Thing", "Mighty Morphin Power Rangers: The Movie",
    "Inspector Gadget", "Turbo Kid", "TMNT", "RoboCop 3", "Spider-Man: Reinforcements",
    "Morbius", "Captain America", "Superhero Movie", "Batman: The Movie", "Old Dogs",
    "Gotham City Sirens", "Max Steel", "Flesh Gordon", "Zoom", "Yeom-lyeok",
    "Underdog", "Batman and Harley Quinn", "The Fantastic Four", "The Shadow", "My Super Ex-Girlfriend",
    "Hercules in New York", "Code Name: Dynastud", "American Splendor", "Unlikely Hero", "Superlópez",
    "Doragon bôru Z: Moetsukiro!! Nessen ressen chô-gekisen", "La mujer murcielago", "Pootie Tang", "Cyborg", "Spider-Man: Into the Spider-Verse 2",
    "Lo chiamavano Jeeg Robot", "Warriors of Virtue", "Rendel", "Condorman", "Adventures of Captain Marvel",
    "The Crow: City of Angels", "Guyver", "The Meteor Man", "Electra", "Untitled Superman Project",
    "The Crow: Wicked Prayer", "Steel", "Shivaay", "Ra.One", "Batgirl",
    "Batman: Return of the Caped Crusaders", "Lobo", "Hancock 2", "Blankman", "Poliziotto superpiù",
    "The Sinister Six", "The Return of Swamp Thing", "Defendor", "The Legend of the Lone Ranger", "Captain America",
    "Black Scorpion", "Spider-Man 2: Another World", "Star Kid", "Krrish 3", "The Crow: Salvation",
    "100 metros", "Zorro: The Gay Blade", "Turbo: A Power Rangers Movie", "Man-Thing", "Guyver: Dark Hero",
    "Jing wu feng yun: Chen Zhen", "Krrish", "Batman", "American Hero", "Scooby-Doo &amp; Batman: The Brave and the Bold",
    "Siu nin Wong Fei Hung chi: Tit ma lau", "Multiple Man", "The Specials", "A Flying Jatt", "Untitled Marvel Project",
    "Doctor Mordrid", "Mind Game", "Batman and Robin", "The Answer", "Shang-Chi",
    "Superman", "It's a Disaster", "Hak hap", "The Toxic Avenger Part II", "Artists and Models",
    "Anniyan", "Antboy", "Silver Surfer: Prodigal Son", "Death of a Superhero", "Il ragazzo invisibile",
    "Irredeemable", "Debiruman", "The Powerpuff Girls Movie", "Spider Man: Lost Cause", "Flash Gordon",
    "Fei Ying", "Nightwing", "Sparks", "Adam Strange", "Untitled Spider-Verse Project",
    "Il ragazzo invisibile: Seconda generazione", "Doragon bôru Z: Sûpâ saiyajin da Son Gokû", "Dragon Ball - Doragon bôru: Shenron no densetsu", "Twice Upon a Time", "The Toxic Avenger Part III: The Last Temptation of Toxie",
    "Rise of the Black Bat", "Black Scorpion II: Aftershock", "Forest Warrior", "Doragon bôru Z: Ginga girigiri!! Butchigiri no sugoi yatsu", "Casshern",
    "Chernaya Molniya", "Jay and Silent Bob's Super Groovy Cartoon Movie", "L'uomo puma", "Podbrosy", "Gekijô-ban - Bishôjo senshi Sêrâ Mûn R",
    "Dai-Nihonjin", "The Return of Captain Invincible", "Untitled Marvel Project", "Untitled Fox/Marvel Film", "The Green Hornet",
    "Xing ying bu li", "Bling", "Pizza Man", "All Superheroes Must Die", "Supergirl",
    "Athena, the Goddess of War", "Sgt. Kabukiman N.Y.P.D.", "Super-Normal", "Storm", "Project Ghazi",
    "Zeroes", "The War Boys", "Jigureul jikyeora!", "143", "Special",
    "Hero at Large", "3 dev adam", "Superman: Requiem", "Lazarus", "ABCs of Superheroes",
    "Kabluey", "Who Would Kill Jessie?", "The Lone Ranger and the Lost City of Gold", "Super Capers: The Origins of Ed and the Missing Bullion", "Alter Egos",
    "The Adventures of Food Boy", "Gekijouban Urutoraman X: Kitazo! Warera no Urutoraman", "Mugamoodi", "Santo Versus the Vampire Women", "The Powerpuff Girls: World",
    "Supersonic Man", "Zhong guo chao ren", "Extranghero", "The Phantom", "Invincible",
    "Untitled Marvel Project", "Black Mask 2: City of Masks", "Gekijô-ban - Bishôjo senshi Sêrâ Mûn S", "Zorro", "Agent 2000: Die Laksman",
    "Dung fong sam hap", "Atom Man vs. Superman", "Doom Patrol", "The Epic Hero and the Beast", "Captain Battle: Legacy War",
    "Recuperando a mi Ex", "Santo and Dracula's Treasure", "Agent Beetle", "Ercole sfida Sansone", "Bishôjo senshi Sêrâ Mûn super S: Sêrâ 9 senshi shûketsu! Burakku dorîmu hôru no kiseki",
    "The Sign of Zorro", "Griff the Invisible", "Daikaijû Batoru: Urutora Ginga Densetsu - The Movie", "Alpha Flight", "Velayudham",
    "Fearless Frank", "Superboy", "Badrinath", "Milarepa", "Yattâman",
    "Mercury Man", "Avenging Force: The Scarab", "Superargo", "Eternal Warrior", "The Projectionist",
    "Capitão Falcão", "Minty: The Assassin", "The Rocketeers", "The Marvelous Spider-Man 3: Empire of Blood", "Rom",
    "Batman: Anarchy", "Mr. Freedom", "Santos", "Body Defenders", "Chôhen kaijû eiga: Urutoraman",
    "Justice Squad", "Nightwatch", "The Fantastic Three", "Thunderstorm: The Return of Thor", "Kamen Raidâ × Supâ Sentai Supâ Hîrô Taisen",
    "Sign Gene", "The Posthuman Project", "Zebraman", "The Green Hornet Strikes Again!", "Uchu Kaisoku-sen",
    "The Green Hornet", "K-20: Kaijin nijû mensô den", "Captain Barbell", "The Marvel Experience", "Le big-Bang",
    "Demon Hunter", "Untitled Fox/Marvel Film", "Silk", "Somebody's Hero", "Robot Ninja",
    "Rat Pfink a Boo Boo", "AranyaDeb", "Fly Me to the Moon", "The Adventures of the American Rabbit", "Los campeones justicieros",
    "Son of Zorro", "Ursus, il terrore dei kirghisi", "Yûsei ôji", "Arrow of the Avenger", "Untitled Fox Marvel Film",
    "Ogenki kurinikku: Tatte moraimasu", "The Spider's Web", "ROM", "The Playmates", "Captain Barbell",
    "Mirageman", "Fury of the Dragon", "À toute épreuve", "Archer &amp; Armstrong", "Lux: Krieger des Lichts",
    "Ercole, Sansone, Maciste e Ursus gli invincibili", "La regina delle Amazzoni", "Harbinger", "Cicak-man", "Supermarsu",
    "Die You Zombie Bastards!", "Inday Bote", "Avengelyne", "Hei bao tian xia", "Untitled Fox/Marvel Film",
    "Super Inday and the Golden Bibe", "Batguano", "Abar", "Bomb Squad", "Batang-X",
    "Untitled Fox/Marvel Film", "Santo vs. la hija de Frankestein", "Untitled Fox/Marvel Film", "Kuen sun", "Santo and the Blue Demon vs. the Monsters",
    "The Bionic Boy", "Santo contra el doctor Muerte", "Blue Demon y Zovek en La invasión de los muertos", "Sidekick", "The Black Pearl",
    "Superargo contro Diabolikus", "Super Hero Party Clown", "The Darkness", "ZsaZsa Zaturnnah Ze Moveeh", "Jealous Gods",
    "Super Noypi", "San kei hap lui", "Ultraman", "Metal Men", "Zorro, the Avenger",
    "Super Mouse and the Roborats", "Quest for Zhu", "Transference: Escape the Dark", "Fenomenal e il tesoro di Tutankamen", "Santo y Blue Demon vs Drácula y el Hombre Lobo",
    "The Indestructible Spider-Man", "Las momias de Guanajuato", "The Photon Effect", "Santo en el museo de cera", "Alyas Batman en Robin",
    "Ultrachrist!", "Flashman", "Dewitt &amp; Maria", "Sansone contro il corsaro nero", "Santo el Enmascarado de Plata vs 'La invasión de los marcianos'",
    "J-Men Forever", "Santo contra los zombies", "Kanthaswamy", "Milarepa", "Lastikman",
    "Spider-Man: Vengeance", "Untitled Franklin Richards Spin-Off", "Cicak Man 3", "Mister X", "Wapakman",
    "El año de la garrapata", "Occhi senza volto", "Dark chaos maze of the universe", "Astro City", "The Avenging Spider-Man",
    "Deathless Man", "Kumander Bawang", "Ang pagbabalik ni Pedro Penduko", "Daikessen! Chô urutora 8 kyôdai", "Santo vs el estrangulador",
    "Biokids", "Cicak-Man 2: Planet Hitam", "B@ (Batman Parody Film)", "Penny Black", "Hoppu suteppu janpu!",
    "Vilaria", "Superman", "Kamen raidâ x Kamen raidâ Fôze &amp; Ôzu Movie taisen Mega Max", "Santo y Blue Demon contra el doctor Frankenstein", "Pedro Penduko, Episode II: The Return of the Comeback",
    "Dynamite Johnson", "Gagamboy", "Kamen Raidâ: The First", "Mighty Mouse in the Great Space Chase", "Flying Guy",
    "American Rescue Squad", "The Book of Secrets", "Youngblood", "Batwoman and Robin", "James Batman",
    "Know Thy Enemy", "El mundo del los muertos", "Surge of Power: The Stuff of Heroes", "The Vampires", "Batang Z",
    "Promedio Rojo", "Gatchaman", "Santo vs. las lobas", "Chôriki sentai Ohranger Vs Kakuranger", "Huck",
    "Santo contra cerebro del mal", "Quantum Theory", "Shock! Shock! Shock!", "The Diabolical Schemes Of Thadeus Jackson", "Il figlio di Zorro",
    "Madman", "Half Dead", "Supermen", "Psychics Tomorrow", "The Almighty Street Team",
    "Super wan-tu-tri", "Spider-Man 2: Rise of Electro", "Das Schicksal von Cysalion", "The Epic of Gilgamesh", "Rubberman",
    "Fantastic Man", "Ang mahiwagang daigdig ni Pedro Penduko", "Qing feng xia", "Champion Road: Arena", "Kamen raidâ Zetto Ô",
    "El barón Brakola", "Daijôbu, mai furendo", "Tao da liang da xian shen wei", "Black Summer", "The Shadow of Zorro",
    "Espectro del estrangulador", "Kamen raidâ × Sûpâ sentai × Uchuu keiji: Supâ hîrô taisen Z", "The Impersonators", "Bakerman", "Untitled Fox/Marvel Film",
    "Shelf Life", "Lastikman", "Super Inday and the Golden Bibe", "Profanadores de tumbas", "Kilink uçan adama karsi",
    "Bagwis", "Atacan las brujas", "SuperAndy, il fratello brutto di Superman", "Dominant Gene", "Down Squad",
    "Superman in Scotland Yard", "Waldo the Dog", "The Green Archer", "Superman in Exile", "Gekkô kamen",
    "La marque de Zorro", "Superhelde", "Hwanggeum nalgae 1.2.3.", "Vuelven los campeones justicieros", "Enigma de muerte",
    "Kabayo Kids", "El robo de las momias de Guanajuato", "Defenders of the Gao", "Super Ranger Kids", "Super Islaw and the Flying Kids",
    "Captain Barbell", "El hacha diabólica", "Harbinger Wars", "Gekijouban Tiger &amp; Bunny: The Beginning", "Supergirl",
    "Night Is Day: The Movie", "Sûpâ jaiantsu", "Eternal", "Superman's Peril", "Superman Flies Again",
    "Dark Fist", "The Adventures of Flash Beaver", "Zorro Rides Again", "Super Idol", "Rock Bottom",
    "Catalina: A New Kind of Superhero", "Cruxman", "Fight! Batman, Fight!", "Black Star and the Golden Bat", "Wu ye tian shi",
    "Seijû sentai Gingaman vs Megaranger", "What Tomorrow Brings", "Darna, Kuno...?", "Doctor D", "Kamen raidaa Jei",
    "Los canallas", "Aimless", "Thunder and Hurricane", "Blue Demon y las invasoras", "Santo contra los cazadores de cabezas",
    "Mighty Man", "Överliggaren", "Sûpâ jaiantsu - Kaiseijin no majô", "Santo contra hombres infernales", "Gekko kamen",
    "Superman and the Jungle Devil", "8 Kamen Riders vs. Galaxy King", "Unsung Heroes", "Kamen Raidaa Bui Surii tai Desutoron Kaijin", "Kamen Rider Super-1: The Movie",
    "Súper Cóndor", "Santo contra los jinetes del terror", "Urutoraman Kosumosu: The First Contact", "The Spider", "Chyornyy frayer",
    "The Crusaders #357: Experiment in Evil!", "Ashoka the Hero", "Night-Wolf", "Gekko kamen - Satan no tsume", "Hero Man",
    "Kimchi Warrior 2D Feast of Fury", "Christian Dreadful", "Supercrooks", "Urutoraman Mebiusu ando Urutora kyôdai", "Binibining Tsuper-Man",
    "Alamid: Ang alamat", "Juan Tanga, super naman, at ang kambal na tiyanak", "Kindergarten Heroes", "The Rising Light", "Kamen Raidâ Burakku: Onigajima he kyûkô seyo!",
    "Diary of a Superhero", "Santo y el águila real", "Ghost of Zorro", "Captain Barbell", "Defective Man!",
    "Revengers Inc.", "Atom Nine Adventures", "Die Flunder", "Wonderguy", "Captain Yagit",
    "Volume", "John's Arm: Armageddon", "Crimson: The Motion Picture", "Paragon", "Love &amp; Plutonium",
    "The Legend of Action Man", "Zero Tolerance", "Mágico, el enviado de los dioses", "Oigyeseo on Ulemae", "Ever Last",
    "Robot Star Jjangga", "Redneck Superheros: The Movie", "Kamagong: Bayani ng Mahirap", "Lonely in London", "Kidlat... ngayon!",
    "Kamen Raidaa Burakku: Kyoufu! Akumatouge no kaijinkan!", "Lastik Man", "Minikin Capital Nights", "Heroes Crossing", "Wonder Vi",
    "The Avenger of Blood: Redemption", "Sûpâ jaiantsu - Uchû kaijin shutsugen", "Kamen Raidaa: Sekai ni kakeru", "Gentleman", "Steel Spirit",
    "Hwarang-V samchongsa", "Cobraman Movie", "Ulemae 7: Dolaon Ulemae", "Our Wonderful World", "Cuatro y medya",
    "DragWorms", "Rape Man: The Night Humper", "Kamen Raidâ X: Go-Nin Raidâ tai kingu Dâku", "Ulemae 4: Thunder V chuldong", "Pedro Penduko",
    "Seupakeumaen", "Jeonja ingan 337", "Babaing kidlat", "Insoluble", "Zoku sûpâ jaiantsu - Akuma no keshin",
    "The Blue Torch", "Hank Is Evil: The Movie", "Oigye Eseo on Ulemae 9: Mujeok Ui Paiteo Ulemae", "Monkey", "Kaiju Big Battel: Terebi Sento",
    "The Magnificent Zorro", "CX2: The Movie", "SupaDupa", "Metalloid: Freshman", "Tinker and Snatch",
    "The Adventures of El Frenetico and Go Girl", "Rosie", "Appu &amp; Gappu International Super Detectives", "Tilkkutäkki", "Oigye uloiyong",
    "New Machine: Ulemae 5", "Bira! Darna! Bira!", "Anak ng kidlat", "Ierô Kiddo", "Je3 sedae: Ulemae 6",
    "The Red Hunter", "Gekkô kamen - Yûrei tô no gyakushû", "Zoku sûpâ jaiantsu", "Eunhaeseo on Byeolddong dongja", "TKO an Human Experiment",
    "The Earl Sessions", "Los maravillosos", "Hanma Kid", "Eunhaeseo on Byeolddong wangja", "Az utolsó nagymester",
    "Oigyeseo on Ulemae 2", "Zoku sûpâ jaiantsu - Dokuga Ôkoku", "Bakas ng gagamba", "Gekko kamen - kaiju Kongu", "Red Rose Concrete",
    "Ulemae 8: Esperman gwa ulemae", "The Orphan: A New Kind of Hero", "Oigye beongaeyong", "Eunhaeseo on Byeolddong wangja je3tan: Eunha yeolcha", "Ang babaeng Isputnik",
    "Oigyeseo on Ulemae 3: Jeongyeok seulijagjeon"
]